/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AllProduct: typeof import('./src/components/homePageSection/AllProduct.vue')['default']
    AuthenticationGraphic: typeof import('./src/components/authenticationComp/AuthenticationGraphic.vue')['default']
    BestSellingProduct: typeof import('./src/components/homePageSection/BestSellingProduct.vue')['default']
    CartDrawer: typeof import('./src/components/cart/CartDrawer.vue')['default']
    Category: typeof import('./src/components/category/Category.vue')['default']
    CategoryItem: typeof import('./src/components/category/CategoryItem.vue')['default']
    CategoryProduct: typeof import('./src/components/homePageSection/CategoryProduct.vue')['default']
    Feature: typeof import('./src/components/feature/Feature.vue')['default']
    FeatureRipple: typeof import('./src/components/feature/FeatureRipple.vue')['default']
    Footer: typeof import('./src/components/footer/Footer.vue')['default']
    Header: typeof import('./src/components/header/Header.vue')['default']
    Hero: typeof import('./src/components/hero/Hero.vue')['default']
    HomeFeature: typeof import('./src/components/feature/HomeFeature.vue')['default']
    PageIntro: typeof import('./src/components/pageExist/PageIntro.vue')['default']
    PopularProduct: typeof import('./src/components/homePageSection/PopularProduct.vue')['default']
    ProductFeature: typeof import('./src/components/feature/ProductFeature.vue')['default']
    ProductItem: typeof import('./src/components/product/ProductItem.vue')['default']
    ProductShow: typeof import('./src/components/homePageSection/ProductShow.vue')['default']
    ProductShowItem: typeof import('./src/components/product/ProductShowItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceFeature: typeof import('./src/components/feature/ServiceFeature.vue')['default']
    ServiceFeatureCard: typeof import('./src/components/feature/ServiceFeatureCard.vue')['default']
    SideCategory: typeof import('./src/components/category/SideCategory.vue')['default']
    SideCategoryItem: typeof import('./src/components/category/SideCategoryItem.vue')['default']
    SignIn: typeof import('./src/components/authenticationComp/SignIn.vue')['default']
    SignUp: typeof import('./src/components/authenticationComp/SignUp.vue')['default']
  }
}
